### ISSUE TITLE
How to solve this issue?

### ISSUE THREAD

**Issue by jerryniu0624** [RS-CSU/MSOCL#3]
`[11/08 19:22:36 fsdet.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800), max_size=800, sample_style='choice'), RandomFlip()]
[11/08 19:22:36 fsdet.data.build]: Using training sampler TrainingSampler
[11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl
Traceback (most recent call last):
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in <module>
    launch(
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch
    main_func(*args)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main
    trainer.resume_or_load(resume=args.resume)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} no`

**Comment by jerryniu0624** [comment]
[11/08 19:22:36 fsdet.data.detection_utils]: TransformGens used in training: [ResizeShortestEdge(short_edge_length=(480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800), max_size=800, sample_style='choice'), RandomFlip()]
[11/08 19:22:36 fsdet.data.build]: Using training sampler TrainingSampler
[11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl
Traceback (most recent call last):
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in <module>
    launch(
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch
    main_func(*args)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main
    trainer.resume_or_load(resume=args.resume)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} no

**Comment by jerryniu0624** [comment]
[11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl
Traceback (most recent call last):
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in <module>
    launch(
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch
    main_func(*args)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main
    trainer.resume_or_load(resume=args.resume)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint ../R-101.pkl not found!

**Comment by qindengda** [comment]
> [11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl Traceback (most recent call last): File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in launch( File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch main_func(*args) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main trainer.resume_or_load(resume=args.resume) File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get( File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load return self.load(path, checkpointables=[]) File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint ../R-101.pkl not found!

This is because you lack the resnet 101 pre training model based on detectron2, which is named R-101.pkl

**Comment by jerryniu0624** [comment]
Thanks a lot！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RS-CSU/MSOCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RS-CSU/MSOCL] How to solve this issue? (Issue #3)





  
[11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl Traceback (most recent call last): File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in launch( File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch main_func(*args) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main trainer.resume_or_load(resume=args.resume) File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get( File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load return self.load(path, checkpointables=[]) File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint ../R-101.pkl not found!
  
This is because you lack the resnet 101 pre training model based on detection2, which is named R-101.pkl

**Comment by jerryniu0624** [comment]
When I replicate your result, some issue occurred. In SPLIT1, 10 shot, resnet101, I used seed1 (total 19 seeds in your published edition) as few shot training novel samples. the result of AP50 is merely 31. However, in your paper, it is 41. Is there any training advice? Thanks a lot!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RS-CSU/MSOCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RS-CSU/MSOCL] How to solve this issue? (Issue #3)





  
[11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl Traceback (most recent call last): File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in launch( File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch main_func(*args) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main trainer.resume_or_load(resume=args.resume) File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get( File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load return self.load(path, checkpointables=[]) File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint ../R-101.pkl not found!
  
This is because you lack the resnet 101 pre training model based on detection2, which is named R-101.pkl

**Comment by jerryniu0624** [comment]
Sorry to bother U. the issue mentioned does not exist, because the AP50 was 51 under that circumstances. That is astonishing. Did I train incorrectly? For example, by only choosing seed1 as few shot samples?




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "RS-CSU/MSOCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RS-CSU/MSOCL] How to solve this issue? (Issue #3)





  
[11/08 19:22:37 fvcore.common.checkpoint]: Loading checkpoint from ../R-101.pkl Traceback (most recent call last): File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 125, in launch( File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch main_func(*args) File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 117, in main trainer.resume_or_load(resume=args.resume) File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 310, in resume_or_load self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get( File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load return self.load(path, checkpointables=[]) File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint ../R-101.pkl not found!
  
This is because you lack the resnet 101 pre training model based on detection2, which is named R-101.pkl
