### ISSUE TITLE
This issue is solved

### ISSUE THREAD

**Issue by jerryniu0624** [RS-CSU/MSOCL#4]
Traceback (most recent call last):
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 127, in <module>
    launch(
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/launch.py", line 52, in launch
    main_func(*args)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 116, in main
    trainer = Trainer(cfg)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/engine/defaults.py", line 270, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/tools/train_net.py", line 84, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/data/build.py", line 217, in build_detection_train_loader
    dataset_dicts = get_detection_dataset_dicts(
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/data/build.py", line 165, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/data/build.py", line 165, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/data/catalog.py", line 62, in get
    return f()
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/data/datasets/meta_dior.py", line 197, in <lambda>
    name, lambda: load_filtered_dior_instances(
  File "/mnt/sde/niuyuanzhuo/MSOCL-main/fsdet/data/datasets/meta_dior.py", line 95, in load_filtered_dior_instances
    with PathManager.open(os.path.join(split_dir,
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/iopath/common/file_io.py", line 1062, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home/niuyuanzhuo/Anaconda3/envs/msocl/lib/python3.8/site-packages/iopath/common/file_io.py", line 645, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/diorsplit/box_10shot_dam_train.txt'

After running prepare_DIOR_few_shot.py successfully, the project structrue become this:

diorsplit/seed(1-19)/box_10shot_dam_train.txt

How to solve this? Thx

**Comment by jerryniu0624** [comment]
![image](https://github.com/RS-CSU/MSOCL/assets/89332323/ec757f95-8ceb-43db-bc95-4f49b7e7e49e)

**Comment by jerryniu0624** [comment]
I ran  python -m tools.train_net --config-file configs/DIOR/split1/10shot_OCL.yml in stage 3

**Comment by jerryniu0624** [comment]
And this issue occurred

**Comment by jerryniu0624** [comment]
This issue is solved
